library(quantmod)
library(fBasics)
library(ggplot2)
a <- read.table("usgbp.txt", header=TRUE)
a$Date <- as.Date(with(a,paste(year,mon,day,sep="-")),"%Y-%m-%d")
a$log_returns <- c(NA,diff(log(a$rate)))
plot(a$Date, a$log_returns, type="l", xlab="Date", ylab="Log Return")
normalTest(a$rate, method="jb")
summary(a$rate)
mean(a$rate)
sd(a$rate)
skewness(a$rate)
kurtosis(a$rate)